spring:
    thymeleaf:
        cache: false
server:
    port: 8080
    ssl:
        enabled: true
        key-store: "server.keystore.jks"
        key-store-password: javaexample
com:
    yoti:
        client:
            clientSdkId: "f4b250fe-124a-4bcc-b0ff-6394ee658248"
            accessSecurityKey: "classpath:/app-keypair.pem"
