spring:
    thymeleaf:
        cache: false
server:
    port: 8080
    ssl:
        enabled: true
        key-store: "server.keystore.jks"
        key-store-password: javaexample
com:
    yoti:
        client:
            clientSdkId: "9b54809d-523f-4f87-befe-020af7d6896d"
            accessSecurityKey: "classpath:/app-keypair.pem"
